import type { Metadata } from "next";
import { Geist, Geist_Mono, Edu_TAS_Beginner } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/lib/auth-context";
import { SessionExpiredModal } from "@/components/session-expired-modal";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const eduTASBeginner = Edu_TAS_Beginner({
  variable: "--font-edu-tas-beginner",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${eduTASBeginner.variable} antialiased`}
      >
        <AuthProvider>
          {children}
          <SessionExpiredModal />
        </AuthProvider>
      </body>
    </html>
  );
}
