"use client";

import Link from "next/link";
import { ArrowRight, Flower, Menu, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Safari } from "@/components/ui/safari";
import { useState } from "react";

const problems = [
  {
    title: "File Duplicate Chaos",
    description: "Excel files multiplied, renamed, and fragmented across teams",
  },
  {
    title: "Formula Breakage Fear",
    description: "Afraid to share or edit files due to formula destruction",
  },
  {
    title: "No Developer Access",
    description: "Can't afford or access developers to build proper tools",
  },
  {
    title: "Manual Time Waste",
    description: "Hours spent on manual data entry and updates",
  },
  {
    title: "No Real-Time Visibility",
    description: "Static files without modern interface or collaboration",
  },
  {
    title: "Broken Workflows",
    description: "Teams can't collaborate without breaking everything",
  },
];

const howItWorks = [
  {
    title: "Upload Your Excel",
    description: "Simply drag and drop your spreadsheet file to get started",
  },
  {
    title: "AI Analyzes Structure",
    description: "Our AI understands your data, formulas, and relationships",
  },
  {
    title: "Generate Components",
    description: "Automatically create forms, tables, and dashboards",
  },
  {
    title: "Deploy Instantly",
    description: "Your web app is live and ready to share with your team",
  },
  {
    title: "Iterate & Improve",
    description: "Make changes and see updates in real-time",
  },
];

const pricingPlans = [
  {
    name: "Starter",
    price: "Free",
    period: "Early Access",
    description: "Perfect for individuals testing the waters",
    features: [
      "1 Excel → Web App conversion",
      "Basic autogenerated UI",
      "GitHub repo creation",
      "Real-time CRUD",
      "Community support",
    ],
    cta: "Get Started Free",
    highlighted: false,
  },
  {
    name: "Pro",
    price: "$5",
    period: "/month",
    description: "For small teams and frequent users",
    features: [
      "Unlimited conversions",
      "Priority UI generation",
      "Custom branding options",
      "Faster deployments",
      "Early access features",
      "Email support",
    ],
    cta: "Start Pro Trial",
    highlighted: true,
  },
  {
    name: "Team",
    price: "$10",
    period: "/seat",
    description: "Perfect for collaborative teams that scale",
    features: [
      "Everything in Pro",
      "Team collaboration features",
      "Admin controls",
      "Private support channel",
      "Enhanced performance",
      "Dedicated onboarding",
    ],
    cta: "Contact Sales",
    highlighted: false,
  },
];

export default function LandingPage() {
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);

  return (
    <div className="min-h-screen bg-[#fff6ed] text-[#424242]">
      {/* Header */}
      <header className="sticky top-0 z-50 bg-[#fff6ed]/95 backdrop-blur-sm">
        <div className="mx-auto flex max-w-[1000px] items-center justify-between px-4 py-4 md:px-5 md:py-5">
          <div className="flex items-center gap-1">
            <svg
              width="62"
              height="14"
              viewBox="0 0 62 14"
              fill="none"
              className="text-[#0d7239]"
            >
              <path d="M0 0H8V2H2V6H7V8H2V12H8V14H0V0Z" fill="currentColor" />
              <path
                d="M10 0H12L15 5L18 0H20L16 7L20 14H18L15 9L12 14H10L14 7L10 0Z"
                fill="currentColor"
              />
              <path d="M22 0H30V2H26V14H24V2H22V0Z" fill="currentColor" />
              <path
                d="M32 0H40V2H34V6H39V8H34V12H40V14H32V0Z"
                fill="currentColor"
              />
              <path
                d="M42 0H48C51.31 0 54 2.69 54 6V8C54 11.31 51.31 14 48 14H42V0ZM48 12C50.21 12 52 10.21 52 8V6C52 3.79 50.21 2 48 2H44V12H48Z"
                fill="currentColor"
              />
              <path d="M56 0H58V14H56V0Z" fill="currentColor" />
              <path d="M60 0H62V14H60V0Z" fill="currentColor" />
            </svg>
            <span className="font-semibold text-[#0d7239] text-sm tracking-wide">
              EXODIA
            </span>
          </div>
          <nav className="hidden items-center gap-8 text-sm md:flex">
            <Link
              href="#"
              className="text-[#424242]/70 transition-colors hover:text-[#0d7239]"
            >
              Home
            </Link>
            <Link
              href="#"
              className="text-[#424242]/70 transition-colors hover:text-[#0d7239]"
            >
              Product
            </Link>
            <Link
              href="#"
              className="text-[#424242]/70 transition-colors hover:text-[#0d7239]"
            >
              Features
            </Link>
            <Link
              href="#"
              className="text-[#424242]/70 transition-colors hover:text-[#0d7239]"
            >
              Pricing
            </Link>
          </nav>
          <div className="flex items-center gap-3 md:gap-4">
            <Link
              href="#"
              className="hidden text-sm text-[#424242]/70 transition-colors hover:text-[#0d7239] md:inline"
            >
              Sign In
            </Link>
            <Button className="hidden bg-[#0d7239] px-4 py-2 text-sm font-semibold text-[#fff6ed] hover:bg-[#0a5c2d] md:inline-flex">
              Get Started
            </Button>
            <button
              className="md:hidden p-2 text-[#0d7239]"
              onClick={() => setMobileMenuOpen(!mobileMenuOpen)}
              aria-label="Toggle menu"
            >
              {mobileMenuOpen ? (
                <X className="w-6 h-6" />
              ) : (
                <Menu className="w-6 h-6" />
              )}
            </button>
          </div>
        </div>

        {/* Mobile Menu */}
        {mobileMenuOpen && (
          <div className="md:hidden bg-[#fff6ed] border-t border-[#0d7239]/20 px-4 py-4">
            <nav className="flex flex-col gap-4">
              <Link
                href="#"
                className="text-[#424242]/70 transition-colors hover:text-[#0d7239] py-2"
                onClick={() => setMobileMenuOpen(false)}
              >
                Home
              </Link>
              <Link
                href="#"
                className="text-[#424242]/70 transition-colors hover:text-[#0d7239] py-2"
                onClick={() => setMobileMenuOpen(false)}
              >
                Product
              </Link>
              <Link
                href="#"
                className="text-[#424242]/70 transition-colors hover:text-[#0d7239] py-2"
                onClick={() => setMobileMenuOpen(false)}
              >
                Features
              </Link>
              <Link
                href="#"
                className="text-[#424242]/70 transition-colors hover:text-[#0d7239] py-2"
                onClick={() => setMobileMenuOpen(false)}
              >
                Pricing
              </Link>
              <Link
                href="#"
                className="text-[#424242]/70 transition-colors hover:text-[#0d7239] py-2"
                onClick={() => setMobileMenuOpen(false)}
              >
                Sign In
              </Link>
              <Button className="w-full bg-[#0d7239] px-4 py-2 text-sm font-semibold text-[#fff6ed] hover:bg-[#0a5c2d]">
                Get Started
              </Button>
            </nav>
          </div>
        )}
      </header>

      {/* Hero Section */}
      <section className="border-b border-l border-r border-dashed border-[rgba(13,114,57,0.5)] mx-4 md:mx-auto max-w-[1000px] overflow-hidden">
        <div className="flex flex-col lg:flex-row items-center justify-between gap-8 lg:gap-10 px-4 md:px-5 py-8 md:py-10">
          <div className="flex flex-col gap-6 md:gap-8 max-w-full lg:max-w-[387px] text-center lg:text-left">
            <h1
              className="font-bold text-3xl md:text-4xl leading-tight"
              style={{ fontFamily: "'Edu TAS Beginner', cursive" }}
            >
              <span className="text-[#0d7239]">Excel</span> to{" "}
              <span className="text-[#0d7239]">Real Web App</span>
              <br />
              in One Click
            </h1>
            <p className="text-[#0d7239] text-sm md:text-base font-medium leading-relaxed">
              Turn the spreadsheets you already trust into living, interactive
              applications — without code, setup, or developers.
            </p>
            <Button className="w-full sm:w-fit mx-auto lg:mx-0 bg-[#0d7239] px-4 py-4 text-sm md:text-base font-semibold text-[#fff6ed] hover:bg-[#0a5c2d]">
              Start Convert Sheets
            </Button>
          </div>
          <div className="relative w-full lg:w-auto">
            <div className="w-full max-w-[480px] mx-auto aspect-square lg:w-[480px] lg:h-[450px] rounded-full bg-[#e8f5e9]/50 flex items-center justify-center p-4 md:p-0">
              <Safari
                url="exodia.app"
                videoSrc="/demo.mp4"
                className="w-full max-w-[480px] shadow-2xl"
              />
            </div>
          </div>
        </div>
      </section>

      {/* Wave Divider */}
      <div className="relative h-[80px] md:h-[150px] overflow-hidden">
        <svg
          className="absolute inset-0 w-full h-full"
          viewBox="0 0 1920 150"
          preserveAspectRatio="none"
        >
          <defs>
            <linearGradient id="waveGradient" x1="0%" y1="0%" x2="100%" y2="0%">
              <stop offset="0%" stopColor="#0d7239" stopOpacity="0.1" />
              <stop offset="50%" stopColor="#0d7239" stopOpacity="0.2" />
              <stop offset="100%" stopColor="#0d7239" stopOpacity="0.1" />
            </linearGradient>
          </defs>
          {[...Array(8)].map((_, i) => (
            <path
              key={i}
              d={`M0 ${75 + i * 5} Q480 ${60 + i * 8} 960 ${75 + i * 5} T1920 ${
                75 + i * 5
              }`}
              fill="none"
              stroke="#0d7239"
              strokeWidth="1"
              strokeOpacity={0.15 + i * 0.02}
            />
          ))}
        </svg>
      </div>

      {/* Problem Section */}
      <section className="border-b border-l border-r border-dashed border-[rgba(13,114,57,0.5)] mx-4 md:mx-auto max-w-[1000px] overflow-hidden px-4 md:px-5 py-6 md:py-8">
        <div className="flex flex-col gap-4 md:gap-5 items-center">
          <p className="text-[#0d7239] text-base md:text-lg font-medium uppercase tracking-wide">
            The Problem
          </p>
          <h2
            className="text-2xl md:text-4xl font-bold text-center"
            style={{ fontFamily: "'Edu TAS Beginner', cursive" }}
          >
            Stop Fighting <span className="text-[#0d7239]">Spreadsheets.</span>
          </h2>
          <p className="text-[#424242]/70 text-sm md:text-base text-center max-w-2xl px-2">
            Non-technical Excel users face a fundamental gap between their data
            and the web applications they need.
          </p>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 w-full mt-4">
            {problems.map((problem, index) => (
              <div key={index} className="rounded-2xl overflow-hidden">
                <div className="h-[160px] sm:h-[200px] md:h-[260px] w-full bg-[#0d7239] rounded-t-2xl" />
                <div className="px-5 md:px-6 py-5 md:py-7 bg-gradient-to-b from-[#a8c5a8] to-[#e8ede4] rounded-b-2xl min-h-[120px] md:min-h-[140px]">
                  <h3 className="text-lg md:text-xl font-semibold text-[#424242] mb-2">
                    {problem.title}
                  </h3>
                  <p className="text-sm md:text-base font-medium text-[#424242]">
                    {problem.description}
                  </p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Wave Divider */}
      <div className="relative h-[80px] md:h-[150px] overflow-hidden">
        <svg
          className="absolute inset-0 w-full h-full"
          viewBox="0 0 1920 150"
          preserveAspectRatio="none"
        >
          {[...Array(8)].map((_, i) => (
            <path
              key={i}
              d={`M0 ${75 + i * 5} Q480 ${60 + i * 8} 960 ${75 + i * 5} T1920 ${
                75 + i * 5
              }`}
              fill="none"
              stroke="#0d7239"
              strokeWidth="1"
              strokeOpacity={0.15 + i * 0.02}
            />
          ))}
        </svg>
      </div>

      {/* Transform Section */}
      <section className="border-b border-l border-r border-dashed border-[rgba(13,114,57,0.5)] mx-4 md:mx-auto max-w-[1000px] overflow-hidden">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-0">
          <div className="px-4 md:px-14 py-8 md:py-12">
            <h2
              className="text-2xl md:text-3xl font-bold leading-tight mb-6 md:mb-8"
              style={{ fontFamily: "'Edu TAS Beginner', cursive" }}
            >
              Transform Your Excel into{" "}
              <span className="text-[#0d7239]">Demand Generation</span>
            </h2>
            <div className="flex flex-col gap-4 md:gap-5 text-[#0d7239]">
              <p className="flex items-start gap-2 text-sm md:text-base">
                <span className="font-medium">→</span>
                Customizable and User-Friendly
              </p>
              <p className="flex items-start gap-2 text-sm md:text-base">
                <span className="font-medium">→</span>
                Build for Enterprises, Not Builders
              </p>
              <p className="flex items-start gap-2 text-sm md:text-base">
                <span className="font-medium">→</span>
                Rapid Excel-based Tooling
              </p>
            </div>
          </div>
          <div className="px-4 md:px-14 py-8 md:py-12 flex items-center border-t md:border-t-0 border-dashed border-[rgba(13,114,57,0.3)]">
            <p
              className="text-[#424242]/80 text-base md:text-lg leading-relaxed italic"
              style={{ fontFamily: "'Edu TAS Beginner', cursive" }}
            >
              &quot;Using traditional methods, building this would&apos;ve taken
              months. Exodia let us deploy a functional web app in just
              days.&quot;
            </p>
          </div>
        </div>
      </section>

      {/* Wave Divider */}
      <div className="relative h-[80px] md:h-[150px] overflow-hidden">
        <svg
          className="absolute inset-0 w-full h-full"
          viewBox="0 0 1920 150"
          preserveAspectRatio="none"
        >
          {[...Array(8)].map((_, i) => (
            <path
              key={i}
              d={`M0 ${75 + i * 5} Q480 ${60 + i * 8} 960 ${75 + i * 5} T1920 ${
                75 + i * 5
              }`}
              fill="none"
              stroke="#0d7239"
              strokeWidth="1"
              strokeOpacity={0.15 + i * 0.02}
            />
          ))}
        </svg>
      </div>

      {/* How It Works Section */}
      <section className="border-b border-l border-r border-dashed border-[rgba(13,114,57,0.5)] mx-4 md:mx-auto max-w-[1000px] overflow-hidden px-4 md:px-5 py-6 md:py-8">
        <div className="flex flex-col gap-4 md:gap-5 items-center">
          <p className="text-[#0d7239] text-base md:text-lg font-medium uppercase tracking-wide">
            How It Works
          </p>
          <h2
            className="text-2xl md:text-4xl font-bold text-center"
            style={{ fontFamily: "'Edu TAS Beginner', cursive" }}
          >
            Five Steps to Your Web App
          </h2>
          <p className="text-[#424242]/70 text-sm md:text-base text-center">
            From spreadsheet to live application in minutes, not months.
          </p>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 w-full mt-4">
            {howItWorks.slice(0, 4).map((step, index) => (
              <div key={index} className="rounded-2xl overflow-hidden">
                <div className="h-[160px] sm:h-[200px] md:h-[260px] w-full bg-[#0d7239] rounded-t-2xl" />
                <div className="px-5 md:px-6 py-5 md:py-7 bg-gradient-to-b from-[#a8c5a8] to-[#e8ede4] rounded-b-2xl min-h-[120px] md:min-h-[140px]">
                  <h3 className="text-lg md:text-xl font-semibold text-[#424242] mb-2">
                    {step.title}
                  </h3>
                  <p className="text-sm md:text-base font-medium text-[#424242]">
                    {step.description}
                  </p>
                </div>
              </div>
            ))}
          </div>

          {/* Fifth step centered */}
          <div className="w-full sm:w-[437px]">
            <div className="rounded-2xl overflow-hidden">
              <div className="h-[160px] sm:h-[200px] md:h-[260px] w-full bg-[#0d7239] rounded-t-2xl" />
              <div className="px-5 md:px-6 py-5 md:py-7 bg-gradient-to-b from-[#a8c5a8] to-[#e8ede4] rounded-b-2xl min-h-[120px] md:min-h-[140px]">
                <h3 className="text-lg md:text-xl font-semibold text-[#424242] mb-2">
                  {howItWorks[4].title}
                </h3>
                <p className="text-sm md:text-base font-medium text-[#424242]">
                  {howItWorks[4].description}
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Wave Divider */}
      <div className="relative h-[80px] md:h-[150px] overflow-hidden">
        <svg
          className="absolute inset-0 w-full h-full"
          viewBox="0 0 1920 150"
          preserveAspectRatio="none"
        >
          {[...Array(8)].map((_, i) => (
            <path
              key={i}
              d={`M0 ${75 + i * 5} Q480 ${60 + i * 8} 960 ${75 + i * 5} T1920 ${
                75 + i * 5
              }`}
              fill="none"
              stroke="#0d7239"
              strokeWidth="1"
              strokeOpacity={0.15 + i * 0.02}
            />
          ))}
        </svg>
      </div>

      {/* Testimonial Section */}
      <section className="border-b border-l border-r border-dashed border-[rgba(13,114,57,0.5)] mx-4 md:mx-auto max-w-[1000px] overflow-hidden px-4 md:px-14 py-8 md:py-12">
        <blockquote
          className="text-lg md:text-2xl font-bold italic leading-relaxed text-center"
          style={{ fontFamily: "'Edu TAS Beginner', cursive" }}
        >
          &quot;Working with this team changed the way we think about pricing
          and growth. We saw clarity, speed and real revenue movement within
          weeks.&quot;
        </blockquote>
        <div className="mt-6 md:mt-8 text-center">
          <p className="font-semibold text-[#0d7239]">Sarah Chen</p>
          <p className="text-sm text-[#424242]/60">Operations Lead, TechCorp</p>
        </div>
      </section>

      {/* Wave Divider */}
      <div className="relative h-[80px] md:h-[150px] overflow-hidden">
        <svg
          className="absolute inset-0 w-full h-full"
          viewBox="0 0 1920 150"
          preserveAspectRatio="none"
        >
          {[...Array(8)].map((_, i) => (
            <path
              key={i}
              d={`M0 ${75 + i * 5} Q480 ${60 + i * 8} 960 ${75 + i * 5} T1920 ${
                75 + i * 5
              }`}
              fill="none"
              stroke="#0d7239"
              strokeWidth="1"
              strokeOpacity={0.15 + i * 0.02}
            />
          ))}
        </svg>
      </div>

      {/* Pricing Section */}
      <section className="border-b border-l border-r border-dashed border-[rgba(13,114,57,0.5)] mx-4 md:mx-auto max-w-[1000px] overflow-hidden px-4 md:px-5 py-6 md:py-8">
        <div className="flex flex-col gap-4 md:gap-5 items-center">
          <p className="text-[#0d7239] text-base md:text-lg font-medium uppercase tracking-wide">
            Pricing
          </p>
          <h2
            className="text-2xl md:text-4xl font-bold text-center"
            style={{ fontFamily: "'Edu TAS Beginner', cursive" }}
          >
            Simple, Transparent Pricing
          </h2>
          <p className="text-[#424242]/70 text-sm md:text-base text-center">
            Choose the plan that fits your needs. Start free, upgrade when
            you&apos;re ready.
          </p>

          <div className="flex flex-col lg:flex-row gap-6 lg:gap-10 items-center lg:items-start justify-center mt-6 w-full">
            {pricingPlans.map((plan, index) => (
              <div
                key={index}
                className={`relative flex flex-col justify-between rounded-lg ${
                  plan.highlighted
                    ? "border-2 border-[#0d7239] order-first lg:order-none"
                    : "border border-[#c8c8c8]"
                } bg-[#fff6ed] px-4 md:px-5 py-6 md:py-8 w-full max-w-[320px] lg:w-[274px]`}
              >
                {plan.highlighted && (
                  <div className="absolute -top-5 left-1/2 -translate-x-1/2">
                    <div className="bg-[#0d7239] rounded-full px-4 md:px-8 py-2 flex items-center gap-2 whitespace-nowrap">
                      <Flower className="w-5 h-5 md:w-6 md:h-6 text-[#fff6ed]" />
                      <span className="text-sm md:text-base font-semibold text-[#fff6ed]">
                        Most Popular
                      </span>
                    </div>
                  </div>
                )}
                <div className="flex flex-col gap-4 md:gap-5">
                  <p className="text-base font-medium text-[#0d7239]">
                    {plan.name}
                  </p>
                  <div className="flex items-center gap-2">
                    <span
                      className="text-[28px] md:text-[32px] font-bold text-[#0d7239]"
                      style={{ fontFamily: "'Edu TAS Beginner', cursive" }}
                    >
                      {plan.price}
                    </span>
                    <span className="text-sm md:text-base font-medium text-[#0d7239]">
                      {plan.period}
                    </span>
                  </div>
                  <p className="text-sm md:text-base font-medium text-[#0d7239]/70">
                    {plan.description}
                  </p>
                  <div className="flex flex-col gap-3 md:gap-5">
                    {plan.features.map((feature, featureIndex) => (
                      <p
                        key={featureIndex}
                        className="text-sm font-medium text-[#0d7239]"
                      >
                        {feature}
                      </p>
                    ))}
                  </div>
                </div>
                <Button
                  className={`w-full py-4 rounded-lg font-semibold text-sm md:text-base mt-6 ${
                    plan.highlighted
                      ? "bg-[#0d7239] text-[#fff6ed] hover:bg-[#0a5c2d]"
                      : "bg-[#f2f2f2] text-[#0d7239] hover:bg-[#e5e5e5]"
                  }`}
                >
                  {plan.cta}
                </Button>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Wave Divider */}
      <div className="relative h-[80px] md:h-[150px] overflow-hidden">
        <svg
          className="absolute inset-0 w-full h-full"
          viewBox="0 0 1920 150"
          preserveAspectRatio="none"
        >
          {[...Array(8)].map((_, i) => (
            <path
              key={i}
              d={`M0 ${75 + i * 5} Q480 ${60 + i * 8} 960 ${75 + i * 5} T1920 ${
                75 + i * 5
              }`}
              fill="none"
              stroke="#0d7239"
              strokeWidth="1"
              strokeOpacity={0.15 + i * 0.02}
            />
          ))}
        </svg>
      </div>

      {/* CTA Section */}
      <section className="border-b border-l border-r border-dashed border-[rgba(13,114,57,0.5)] mx-4 md:mx-auto max-w-[1000px] overflow-hidden px-4 md:px-14 py-8 md:py-12">
        <div className="text-center">
          <h2
            className="text-2xl md:text-4xl font-bold mb-4"
            style={{ fontFamily: "'Edu TAS Beginner', cursive" }}
          >
            Ready to Transform Your Excel?
          </h2>
          <p className="text-[#424242]/70 text-sm md:text-base max-w-2xl mx-auto mb-6 md:mb-8">
            Join hundreds of businesses already building web apps from their
            spreadsheets. Limited early access spots available.
          </p>
          <div className="flex flex-col sm:flex-row items-center justify-center gap-4 sm:gap-8">
            <Button className="w-full sm:w-auto bg-[#0d7239] px-6 md:px-8 py-4 md:py-6 text-sm md:text-base font-semibold text-[#fff6ed] hover:bg-[#0a5c2d] flex items-center justify-center gap-2">
              Claim Early Access
              <ArrowRight className="w-5 h-5 md:w-6 md:h-6" />
            </Button>
            <Button
              variant="outline"
              className="w-full sm:w-auto border border-[#0d7239] bg-transparent px-6 md:px-8 py-4 md:py-6 text-sm md:text-base font-semibold text-[#0d7239] hover:bg-[#0d7239]/5"
            >
              See Demo
            </Button>
          </div>
          <p className="mt-6 md:mt-8 text-sm md:text-base text-[#424242]/70">
            No credit card required • Free tier available forever
          </p>
        </div>
      </section>

      {/* Wave Divider */}
      <div className="relative h-[80px] md:h-[150px] overflow-hidden">
        <svg
          className="absolute inset-0 w-full h-full"
          viewBox="0 0 1920 150"
          preserveAspectRatio="none"
        >
          {[...Array(8)].map((_, i) => (
            <path
              key={i}
              d={`M0 ${75 + i * 5} Q480 ${60 + i * 8} 960 ${75 + i * 5} T1920 ${
                75 + i * 5
              }`}
              fill="none"
              stroke="#0d7239"
              strokeWidth="1"
              strokeOpacity={0.15 + i * 0.02}
            />
          ))}
        </svg>
      </div>

      {/* Footer */}
      <footer className="mx-auto max-w-[1000px] px-4 md:px-14 py-8 md:py-12">
        <div className="flex flex-col md:flex-row justify-between gap-8 md:gap-0">
          <div className="max-w-full md:max-w-[280px]">
            <div className="flex items-center gap-1 mb-4">
              <svg
                width="62"
                height="14"
                viewBox="0 0 62 14"
                fill="none"
                className="text-[#0d7239]"
              >
                <path d="M0 0H8V2H2V6H7V8H2V12H8V14H0V0Z" fill="currentColor" />
                <path
                  d="M10 0H12L15 5L18 0H20L16 7L20 14H18L15 9L12 14H10L14 7L10 0Z"
                  fill="currentColor"
                />
                <path d="M22 0H30V2H26V14H24V2H22V0Z" fill="currentColor" />
                <path
                  d="M32 0H40V2H34V6H39V8H34V12H40V14H32V0Z"
                  fill="currentColor"
                />
                <path
                  d="M42 0H48C51.31 0 54 2.69 54 6V8C54 11.31 51.31 14 48 14H42V0ZM48 12C50.21 12 52 10.21 52 8V6C52 3.79 50.21 2 48 2H44V12H48Z"
                  fill="currentColor"
                />
                <path d="M56 0H58V14H56V0Z" fill="currentColor" />
                <path d="M60 0H62V14H60V0Z" fill="currentColor" />
              </svg>
              <span className="font-semibold text-[#0d7239] text-sm tracking-wide">
                EXODIA
              </span>
            </div>
            <p className="text-sm text-[#424242]/60 leading-relaxed">
              Transform Excel files into web apps instantly.
            </p>
          </div>

          <div className="grid grid-cols-2 sm:grid-cols-4 gap-6 md:gap-12 lg:gap-24">
            <div>
              <p className="mb-3 md:mb-4 text-sm font-semibold text-[#424242]">
                Product
              </p>
              <ul className="space-y-2 text-sm text-[#424242]/60">
                <li>
                  <Link href="#" className="hover:text-[#0d7239]">
                    Features
                  </Link>
                </li>
                <li>
                  <Link href="#" className="hover:text-[#0d7239]">
                    Pricing
                  </Link>
                </li>
                <li>
                  <Link href="#" className="hover:text-[#0d7239]">
                    Changelog
                  </Link>
                </li>
                <li>
                  <Link href="#" className="hover:text-[#0d7239]">
                    Roadmap
                  </Link>
                </li>
              </ul>
            </div>
            <div>
              <p className="mb-3 md:mb-4 text-sm font-semibold text-[#424242]">
                Resources
              </p>
              <ul className="space-y-2 text-sm text-[#424242]/60">
                <li>
                  <Link href="#" className="hover:text-[#0d7239]">
                    Documentation
                  </Link>
                </li>
                <li>
                  <Link href="#" className="hover:text-[#0d7239]">
                    Tutorials
                  </Link>
                </li>
                <li>
                  <Link href="#" className="hover:text-[#0d7239]">
                    Blog
                  </Link>
                </li>
                <li>
                  <Link href="#" className="hover:text-[#0d7239]">
                    Community
                  </Link>
                </li>
              </ul>
            </div>
            <div>
              <p className="mb-3 md:mb-4 text-sm font-semibold text-[#424242]">
                Company
              </p>
              <ul className="space-y-2 text-sm text-[#424242]/60">
                <li>
                  <Link href="#" className="hover:text-[#0d7239]">
                    About
                  </Link>
                </li>
                <li>
                  <Link href="#" className="hover:text-[#0d7239]">
                    Careers
                  </Link>
                </li>
                <li>
                  <Link href="#" className="hover:text-[#0d7239]">
                    Press
                  </Link>
                </li>
                <li>
                  <Link href="#" className="hover:text-[#0d7239]">
                    Contact
                  </Link>
                </li>
              </ul>
            </div>
            <div>
              <p className="mb-3 md:mb-4 text-sm font-semibold text-[#424242]">
                Legal
              </p>
              <ul className="space-y-2 text-sm text-[#424242]/60">
                <li>
                  <Link href="#" className="hover:text-[#0d7239]">
                    Privacy
                  </Link>
                </li>
                <li>
                  <Link href="#" className="hover:text-[#0d7239]">
                    Terms
                  </Link>
                </li>
                <li>
                  <Link href="#" className="hover:text-[#0d7239]">
                    Security
                  </Link>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </footer>

      {/* Large EXODIA text */}
      <div className="overflow-hidden py-6 md:py-12">
        <h2
          className="text-center font-bold text-[60px] sm:text-[100px] md:text-[140px] lg:text-[175px] leading-none tracking-tight text-[#0d7239]/10"
          style={{ fontFamily: "'Edu TAS Beginner', cursive" }}
        >
          EXODIA
        </h2>
      </div>
    </div>
  );
}
