import { PricingCard } from "./pricing-card";

const pricingPlans = [
  {
    name: "Starter",
    price: "Free",
    period: "Early Access",
    description: "Perfect for individuals testing the waters",
    features: [
      "1 Excel → Web App conversion",
      "Basic autogenerated UI",
      "GitHub repo creation",
      "Real-time CRUD",
      "Community support",
    ],
    cta: "Get Started Free",
    highlighted: false,
  },
  {
    name: "Pro",
    price: "$5",
    period: "/month",
    description: "For small teams and frequent users",
    features: [
      "Unlimited conversions",
      "Priority UI generation",
      "Custom branding options",
      "Faster deployments",
      "Early access features",
      "Email support",
    ],
    cta: "Start Pro Trial",
    highlighted: true,
  },
  {
    name: "Team",
    price: "$10",
    period: "/seat",
    description: "Perfect for collaborative teams that scale",
    features: [
      "Everything in Pro",
      "Team collaboration features",
      "Admin controls",
      "Private support channel",
      "Enhanced performance",
      "Dedicated onboarding",
    ],
    cta: "Contact Sales",
    highlighted: false,
  },
];

export function PricingSection() {
  return (
    <section className="mx-4 md:mx-auto max-w-[1000px] overflow-hidden px-4 md:px-5 py-6 md:py-8">
      <div className="flex flex-col gap-4 md:gap-5 items-center">
        <p className="text-[#0d7239] text-base md:text-lg font-medium uppercase tracking-wide">
          Pricing
        </p>
        <h2
          className="text-2xl md:text-4xl font-bold text-center"
          style={{ fontFamily: "'Edu TAS Beginner', cursive" }}
        >
          Simple, Transparent Pricing
        </h2>
        <p className="text-[#424242]/70 text-sm md:text-base text-center">
          Choose the plan that fits your needs. Start free, upgrade when
          you&apos;re ready.
        </p>

        <div className="flex flex-col lg:flex-row gap-6 lg:gap-10 items-center lg:items-start justify-center mt-6 w-full">
          {pricingPlans.map((plan, index) => (
            <PricingCard
              key={index}
              name={plan.name}
              price={plan.price}
              period={plan.period}
              description={plan.description}
              features={plan.features}
              cta={plan.cta}
              highlighted={plan.highlighted}
            />
          ))}
        </div>
      </div>
    </section>
  );
}

