"use client";

import { PricingCard } from "./pricing-card";
import { motion } from "motion/react";

const pricingPlans = [
  {
    name: "Starter",
    price: "Free",
    period: "Early Access",
    description: "Perfect for individuals testing the waters",
    features: [
      "1 Excel → Web App conversion",
      "Basic autogenerated UI",
      "GitHub repo creation",
      "Real-time CRUD",
      "Community support",
    ],
    cta: "Get Started Free",
    highlighted: false,
  },
  {
    name: "Pro",
    price: "$5",
    period: "/month",
    description: "For small teams and frequent users",
    features: [
      "Unlimited conversions",
      "Priority UI generation",
      "Custom branding options",
      "Faster deployments",
      "Early access features",
      "Email support",
    ],
    cta: "Start Pro Trial",
    highlighted: true,
  },
  {
    name: "Team",
    price: "$10",
    period: "/seat",
    description: "Perfect for collaborative teams that scale",
    features: [
      "Everything in Pro",
      "Team collaboration features",
      "Admin controls",
      "Private support channel",
      "Enhanced performance",
      "Dedicated onboarding",
    ],
    cta: "Contact Sales",
    highlighted: false,
  },
];

export function PricingSection() {
  return (
    <section
      id="pricing"
      className="mx-4 md:mx-auto max-w-[1000px] overflow-hidden px-4 md:px-5 py-6 md:py-8"
    >
      <div className="flex flex-col gap-4 md:gap-5 items-center">
        <motion.p
          className="text-[#0d7239] text-base md:text-lg font-medium uppercase tracking-wide"
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5 }}
        >
          Pricing
        </motion.p>
        <motion.h2
          className="text-2xl md:text-4xl font-bold text-center"
          style={{ fontFamily: "'Edu TAS Beginner', cursive" }}
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5, delay: 0.1 }}
        >
          Simple, Transparent Pricing
        </motion.h2>
        <motion.p
          className="text-[#424242]/70 text-sm md:text-base text-center"
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5, delay: 0.2 }}
        >
          Choose the plan that fits your needs. Start free, upgrade when
          you&apos;re ready.
        </motion.p>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 lg:gap-10 justify-items-center mt-6 w-full">
          {pricingPlans.map((plan, index) => (
            <PricingCard
              key={index}
              name={plan.name}
              price={plan.price}
              period={plan.period}
              description={plan.description}
              features={plan.features}
              cta={plan.cta}
              highlighted={plan.highlighted}
              index={index}
            />
          ))}
        </div>
      </div>
    </section>
  );
}
